config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resource :users do
    get '/user_profile', to: 'users#user_profile'
  end
  resources :likes, only: %i[create destroy index]
  resource :reports, only: %i[create destroy] do
    collection do
      get '/reported_post', to: 'reports#all_reported_post'
      get '/reported_comment', to: 'reports#all_reported_comment'
      post '/search_post', to: 'posts#search'
    end
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy index show]
    resources :suggestions
  end
  get '/comments/:id', to: 'comments#index'

  root to: 'pages#home'
end

app/models/like.rb
# frozen_string_literal: true

# Doc for the class
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  scope :latest, -> { order(updated_at: :desc).last(10) }
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[destroy]

  skip_before_action :verify_authenticity_token

  def create
    @like = Like.new(like_params)
    respond_to do |format|
      if @like.save
        @like_class = (@like.likeable.class.to_s).eql?(CONSTANTS[:COMMENT])
        format.json { render json: get_post, status: :ok }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { status: 404, message: 'Fail to create record' } }
      end
      format.js
    end
  end

  def destroy
    @like_class = (@post.likeable.class.to_s).eql?(CONSTANTS[:COMMENT])
    if @post.destroy
      respond_to do |format|
        format.json { render json: get_post }
        format.js
      end
    else
      respond_to do |format|
        format.json { render json: { status: 204, message: 'Fail to delete record' } }
      end
    end

  private

  def set_likeable
    @likeable = like_params[:likeable_type].constantize.find(like_params[:likeable_id])
  end

  def set_post

    @post = Like.find_by(user_id: like_params[:user_id], id: params[:id].to_i)
  end

  def get_post
    @current_post = if like_params[:likeable_type] === 'Post'
                      Post.find_by(id: like_params[:likeable_id])
                    else
                      Comment.find_by(id: like_params[:likeable_id]).post
                    end
    @current_post.to_json(include: :likes, include: { comments: { include: :replies } })

  end

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type, :user_id)
  end
end

app/views/likes/_likeBtn.html.erb
<div id="testing">
    <div id="likecount_<%=likeable.id%>_<%=likeable.user.id %>" class="mb-2" >
        <% like = Like.find_by(likeable:likeable,user_id:current_user.id)%>
        <%if like.nil?%>
            <%= form_tag( "/likes" , remote: true) do |f| %>
                <input type="hidden" name="like[likeable_id]" value="<%= likeable.id%>">
                <input type="hidden" name="like[likeable_type]" value="<%= likeable.class.to_s%>">
                <input type="hidden" name="like[user_id]" value="<%= current_user.id%>">

                <div class="d-flex like-cnt">
                    <div id="post_comment_<%=likeable.id%>" class="mr-2 like-cnt-div">
                        <% likes=likeable.likes.count%>
                        <%if likes>0%>
                              <%=likes%>      
                        <%else%>
                            
                        <%end%>
                    </div>
                    <input type="submit" value="like Me " class="btn btn-primary">
                </div>
            <% end %>
            <%else%>
                <%= form_tag(like_path(like) , remote: true) do |f| %>
                <input type="hidden" name="_method" value="DELETE">
                <div class="like-cnt" >
                    <div id="post_comment_<%=likeable.id%>" class="mr-2 like-cnt-div">
                        <%= likeable.likes.count%> 
                    </div>
                    <input type="hidden" name="like[user_id]" value="<%= current_user.id%>">
                    <input type="submit" value="Unlike" class="btn btn-danger">
                </div>
            <% end %>
        <%end%>
    <div>    
</div>

app/views/likes/create.js.erb
<%if((@post.likeable.class.to_s).eql?(CONSTANTS[:COMMENT]))%>
    $("#post_comment").empty().append(`<%= j render @post.likeable.post.comments.where(reply_id: nil).order(id: :desc)%>`);
<%else%>
    $("#likecount_<%=@post.likeable.id%>_<%=@post.likeable.user.id%>").empty().append(`<%= j render partial: "likes/likeBtn", locals:{likeable:@post.likeable}%>`);
<%end%>
   

app/views/likes/destroy.js.erb
<%if(@like_class)%>
    $("#post_comment").empty().append(`<%= j render @post.likeable.post.comments.where(reply_id: nil).order(id: :desc)%>`);
<%else%>
    $("#likecount_<%=@post.likeable.id%>_<%=@post.likeable.user.id%>").empty().append(`<%= j render partial: "likes/likeBtn", locals:{likeable:@post.likeable}%>`);
<%end%>
   