config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resource :users do
    get '/user_profile', to: 'users#user_profile'
  end
  resources :likes, only: %i[create destroy index]
  resource :reports, only: %i[create destroy] do
    collection do
      get '/reported_post', to: 'reports#all_reported_post'
      get '/reported_comment', to: 'reports#all_reported_comment'
      post '/search_post', to: 'posts#search'
    end
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy index show]
    resources :suggestions
  end
  get '/comments/:id', to: 'comments#index'

  root to: 'pages#home'
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Blog App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <%if current_user%>
        <%if current_user.role === "regular_user"%>
          <li class="nav-item">
            <%= link_to "All My Suggestion",suggestion_path(current_user.id),class:"nav-link" %>
          </li>

          <li class="nav-item"><a class="nav-link" href="/users/user_profile">User Profile</a></li>
        <%end%>
      <%end%>
         <%if current_user && current_user.role==="admin"%>
            <a class="nav-link" href="/admin">Admin Dashboard</a>
         <%end%>
      <%if current_user && current_user.role==="moderator"%>
          <li class="nav-item">
            <a class="nav-link" href="<%= reported_post_reports_path%>">Reported Post</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= reported_comment_reports_path%>">Reported Comments</a>
          </li>
      <%else%>
        <div></div>
      <%end%>
  
      <%if current_user%>
        <li class="nav-item">
          <a class="nav-link" href="<%= posts_path%>">All Post</a>
        </li>
        <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete,class:"nav-link"%>
        </li>
      <%else%>
         <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
        </li>
      <%end%>
        <%if current_user%>
          <%if current_user.role === "regular_user"%>
          <%end%>
      <%end%>
    </ul>
  </div>
  <%if current_user%>
   <div class="d-flex justify-content-end ml-10">
        <li class="p-2 mr-2 px-4 nav-tags"><%=current_user.role%></li>
      <li class="p-2 px-4 nav-tags"><%=current_user.email%></li>
    </div>
    <%if current_user.role === "regular_user"%>    
    <%end%>
<%end%>
</nav>