config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resource :users do
    get '/user_profile', to: 'users#user_profile'
  end
  resources :likes, only: %i[create destroy index]
  resource :reports, only: %i[create destroy] do
    collection do
      get '/reported_post', to: 'reports#all_reported_post'
      get '/reported_comment', to: 'reports#all_reported_comment'
      post '/search_post', to: 'posts#search'
    end
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy index show]
    resources :suggestions
  end
  get '/comments/:id', to: 'comments#index'

  root to: 'pages#home'
end

app/models/post.rb
# frozen_string_literal: true

# Doc for the class
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  has_many :suggestions, dependent: :destroy

  validates :content, :title, presence: true

  has_rich_text :content

  enum status: { published: 0, unpublished: 1 }

  scope :latest, -> { where(status: CONSTANTS[:PUBLISHED]).order(updated_at: :desc).last(10) }
  scope :search_by_field_substring, lambda { |query|
    where('title ILIKE ?', "%#{query}%")
  }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show update destroy]
  before_action :get_post, only: %i[show]
  skip_before_action :verify_authenticity_token

  def index
    @posts = Post.includes(:likes, comments: :replies)
    respond_to do |format|
      format.html
      format.json { render json: @posts, each_serializer: PostSerializer }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @post.to_json(include: :likes, include: { comments: { include: :replies } }) }      
    end
  end

  def new
    authorize Post
    @post = current_user.posts.new
  end

  def create
    
    @post = Post.new(post_params)
    @post.status = :unpublished
    respond_to do |format|
      if @post.save
        format.json { render json: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { status: 404, message: 'Fail to create record' } }
      end
      format.js
    end
  end

  def update
    
    respond_to do |format|
      if @post.update(post_params)
        format.json { render json: @post }
        format.html { redirect_to post_url(@post), notice: t('errors.update_post') }
      else
        format.json { render json: { status: 204, message: 'Fail to update record' } }
      end
      format.js
    end
  end

  def destroy
    authorize Post
    @post.destroy
    respond_to do |format|
      format.js
    end
  end

  def search
    @posts = if post_params[:title].length.positive?
               Post.search_by_field_substring(post_params[:title])
             else
               Post.all
             end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :links, :status, :title, :user_id)
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: Post.new, local: false) do |form| %>


   <div class="field">
    <%= form.label :title %>
    <input name="post[title]" class="form-control" placeholder="Enter Title" id="form_title_input"/>
  </div>

    <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content, :class=>"form-control", :id=>"exampleFormControlTextarea2", :rows=>"3"%>
  </div>

  <div class="field">
 
    <input hidden type="text" name="post[status]" value="<%=Post.statuses[1]%>"/>
    <input hidden type="text" name="post[user_id]" value="<%=current_user.id%>"/>

  </div>
 <div class="actions">
    <%= form.submit :class=>"btn btn-primary w-100" %>
  </div> 
<% end %>

app/views/posts/_post.html.erb
<div id="post_<%=post.id%>">
  <div class="blog-container">
    <div class="blog-header">
      <div class="blog-author--no-cover">
        <h3 class="post-h3"><%= post.user.email%> | <%= post.status%> | <%= link_to "Post", post_path(post.id) %></h3> 
      </div>
      <%if current_user.role === "moderator"%>
        <%= form_with(model: post, local: false) do |form| %>
          <div class="d-flex flex-col justify-content-end align-items-center">
              <div class="field">
                <%= form.label :status %>
                <%= form.select :status, options_for_select(Post.statuses.map { |key, value| [key.humanize, key] }), {prompt: "Select Status"}, class: "form-control" %>

              </div>
              <div class="actions mt-4 pt-2 ml-2 mr-2">
                <%= form.submit :class=>"btn btn-primary w-100" %>
              </div> 
          </div> 
        <% end %>
      <%else%>
      <%end%>
    </div>

    <div class="blog-body">
      <div class="blog-title">
        <h1 class=""><%= link_to post.title, post %></h1>
      </div>
    </div>

    <div class="blog-footer">
      <ul class="mt-4">
        <li class="published-date"><%= time_ago_in_words(post.updated_at)%></li>
        <li class="comments "><a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
              fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
              <path
                d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
            </svg><span class="numero"><%= post.likes.count%></span></a></li>
        <li class="shares"><a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
              fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
              <path
                d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
            </svg><span class="numero"><%= post.comments.count%></span></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/posts/_updateForm.html.erb
<%= form_with(model: post, local: true) do |form| %>
 

    <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content, :class=>"form-control", :id=>"exampleFormControlTextarea1", :rows=>"3"%>
  </div>
  <div class="field">
    <%= form.label :status %>
    <input type="text" disabled name="post[status]" value="published"/>

  </div>
 <div class="actions">
    <%= form.submit :class=>"btn btn-primary w-100" %>
  </div> 
<% end %>

app/views/posts/create.js.erb
$("#exampleModalCenter").modal("hide")

$("#exampleFormControlTextarea2").val("")
$("#form_title_input").val("")

$("#post-message").empty().append(`<div><%= t "errors.review"%></div>`)

<%if @post.errors.full_messages.length>0%>
    $("#post-message").empty().append(`<div><%= t "errors.empty_feilds"%></div>`)
<%end%>

app/views/posts/destroy.js.erb
$("#reported_post_<%=@post.id%>").remove()

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'updateForm', post: @post %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/edit.js.erb
$("#reported_post_<%=@post.id%>").remove()

app/views/posts/index.html.erb
  <%if current_user.role === "regular_user"%>
 <button type="button" class="btn btn-primary flex justify-center w-80 ml-3" data-toggle="modal" data-target="#exampleModalCenter">
            Create New Post
          </button>
<%end%>
<div class="d-flex justify-content-center ">
       <%if current_user.role === "regular_user"%>
          <input id="searchInput" onkeyup="debounce()"  class="searchposts mr-1" type="text" name="search" placeholder="Search..">
          <%else%>
        <%end%>     
</div>
<%if current_user.role==="regular_user"%>
          <!-- Modal -->
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= render partial: "form"%>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
<%end%>

 <div id="post_containor">
    <%if current_user.role === "moderator"%>
        <%if @posts.count===0%>
            <div class="d-flex justify-content-center align-items-center">
                No Record Found
            </div>  
        <%else%>
            <%= render @posts.where(status: "unpublished").order(updated_at: :desc)%>
        <%end%> 
    <%else%>
       <div id="postSeachByUser">
        <%if @posts.count===0%>
            <div class="d-flex justify-content-center align-items-center alert alert-primary mt-10">
                No Record Found
            </div>  
        <%else%>
            <%= render @posts.where(status: "published").order(updated_at: :desc)%> 
        <%end%> 
       </div>
    <%end%>
 </div>

<%if current_user.role === "regular_user"%>
  <%
=begin%>
 <div class="d-flex justify-content-center"> <%== pagy_nav(@pagy) %></div> 
<%
=end%>
<%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/search.js.erb
$("#postSeachByUser").empty().append(`
    <%if @posts.count===0%>
            <div class="d-flex justify-content-center align-items-center alert alert-primary mt-10">
                No Record Found
            </div>  
        <%else%>
            <%= j render @posts.where(status: "published").order(updated_at: :desc)%> 
        <%end%>
`)

app/views/posts/show.html.erb
<div class="col-lg-8 mx-lg-auto px-2">
  <div class="card shadow">
    <div class="card-header">
      <h2 class="card-title text-center"></h2>
      <div class="d-flex justify-content-end">
        <%if current_user.id == @post.user.id%>
            <%= link_to 'Edit', edit_post_path(@post) ,:class=>"btn btn-primary active mr-3"%> 
        <%else%>
        <%end%>

      <div class="btn-group">
        <%= link_to 'Back', posts_path,:class=>"btn btn-primary active" %>
      </div>
  </div>
</div>

<div class="p-2">
    <p class="post_title">
      <%= @post.title %>
    </p>
    <div class="tags-post ">
      <strong>Status:</strong>
      <div class="ml-2 tags-post-cont"> <%= @post.status %></div>
    </div>
    <p>
    <strong>Content:</strong>
      <%= @post.content %>
    </p>
    <div class="d-flex align-items-center">
      <%if current_user.role ==="regular_user"%>
          <%
=begin%>
 <button type="button" class="btn btn-primary flex justify-center" data-toggle="modal" data-target="#suggestionModalCenter">
              Create Suggestion 
          </button> 
<%
=end%>
      <%else%>
      <%end%>
      <%
=begin%>
 <div id="post_suggeston_counts"> (<a id="post_suggeston_count" href="<%= post_suggestions_path(@post) %>"><%= @post.suggestions.count%> Post Suggestion</a>)</div> 
<%
=end%>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="suggestionModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="e xampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "suggestions/form", locals:{post:@post}%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%if current_user.role==="regular_user"%>
    <div class="like-report mt-2">
        <div id="show-post-like d-inline w-15">
          <%=render partial: "likes/likeBtn", locals:{likeable:@post}%>
        </div>
      
        <%
=begin%>
 <div id="report_<%= @post.id%>" >
            <%=  render partial:"reports/form", locals:{ reportable:@post }%>
        </div> 
<%
=end%>
      </div>
  <%else%>
  <%end%>
  <hr/>

<div>
  <%if current_user.role==="regular_user"%>
  <div>
    <strong>
    Post Comments
    <strong>
      <div id="post_comment">
        <div>
              <%= render @post.comments.where(reply_id: nil).order(id: :desc)%>
        </div>
      </div>
      <div>
        <%= render partial:"comments/form", locals:{post:@post, parent: nil} %>
      </div>
  </div>
<%else%>

<%end%>
</div>

app/views/posts/update.js.erb
$("#post_<%=@post.id%>").remove()
$("#reported_post_<%=@post.id%>").remove()