config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resource :users do
    get '/user_profile', to: 'users#user_profile'
  end
  resources :likes, only: %i[create destroy index]
  resource :reports, only: %i[create destroy] do
    collection do
      get '/reported_post', to: 'reports#all_reported_post'
      get '/reported_comment', to: 'reports#all_reported_comment'
      post '/search_post', to: 'posts#search'
    end
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy index show]
    resources :suggestions
  end
  get '/comments/:id', to: 'comments#index'

  root to: 'pages#home'
end

app/models/report.rb
# frozen_string_literal: true

# Documentation for the Class
class Report < ApplicationRecord
  # foreign Keys
  belongs_to :user
  belongs_to :reportable, polymorphic: true

  validates :report_status, presence: true

  scope :reported_comments, -> { where(reportable_type: CONSTANTS[:COMMENT]) }
  scope :reported_posts, -> { where(reportable_type: CONSTANTS[:POST]) }
  scope :un_reported_status, -> { where.not(report_status: nil) }
  scope :user_reported_posts, ->(id) { reported_posts.where(reportable_id: id) }
  scope :user_reported_comments, ->(id) { reported_comments.where(reportable_id: id) }
  scope :remove_post_duplicate, -> { select('DISTINCT ON (reportable_id) *').reported_posts.un_reported_status }
  scope :remove_comment_duplicate, -> { select('DISTINCT ON (reportable_id) *').reported_comments.un_reported_status }

  enum report_status: { abusive: 0, under18: 1 }
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report, only: %i[destroy]
  before_action :set_reportable, only: %i[create]

  def create
    authorize Report
    # @report = current_user.reports.new(report_params)

    @report = @reportable.reports.new(report_params)
    @report.user_id = current_user.id

    respond_to do |format|
      if @report.save
        @post = Report.find(id: @report.reportable_id)
        @post = @report.reportable
      else
        format.html { render :new, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def destroy
    authorize Report
    @post = @report.reportable
    @report.destroy
    respond_to do |format|
      format.js
    end
  end

  def all_reported_post
    authorize Report
    @reported_posts = Report.remove_post_duplicate
  end

  def all_reported_comment
    authorize Report
    @reported_comments = Report.remove_comment_duplicate
  end

  private

  def set_reportable
    @reportable = report_params[:reportable_type].constantize.find(report_params[:reportable_id])
  end

  def set_report
    @report = current_user.reports.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:reportable_id, :reportable_type, :report_status)
  end
end

app/views/reports/_form.html.erb
<% like = current_user.reports.find_by(reportable:reportable)%>
        <%if like.nil?%>
            <%= form_with(url:reports_path, local: false) do |form| %>
           <div class="d-flex mt-2 mb-2">    
                <div class="field mr-2">
                <%= form.select :report_status, options_for_select(Report.report_statuses.map { |key, value| [key.humanize, key] }), {prompt: "Select Status"}, class: "form-control" %>

                   
                </div>
                <input type="hidden" name="report[reportable_id]" value=" <%=reportable.id %>">
                <input type="hidden" name="report[reportable_type]" value="<%=reportable.class.to_s%>">
                <div class="actions d-inline">
                    <input type="submit" class="btn btn-primary p-1" value="Report <%=reportable.class.to_s%>">
                </div>
                </div>
            <%end%>
        <%else%>
            <div></div>
        <% end %>

app/views/reports/_report_modal.html.erb
  <div class="modal fade" id="exampleModal<%=report.reportable.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <% all_reportee = Report.user_reported_posts(report.reportable_id).order(updated_at: :desc)%>
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Reported By</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%all_reportee.each do |user|%>
                    <div class="reported-card">
                        <img class="rounded-circle shadow-1-strong me-3 mr-2"
                            src="https://thumbs.dreamstime.com/b/person-gray-photo-placeholder-man-costume-background-146157490.jpg" alt="avatar" width="60" height="60" />
                        <p>
                            <%= user.user.email%>
                        <p> 
                        <p>
                            <%=time_ago_in_words(user.created_at) %>
                        <p> 
                    </div>
                 
                <%end%>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary w-100" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
    </div>

app/views/reports/_reported_comment.html.erb
<div id="reported_comment_<%= reported_comment.reportable.id%>" class="comment-card">
    <%= render partial:"report_modal", locals:{report:reported_comment} %>
    <div class="modal fade" id="exampleModal<%=reported_comment.reportable.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <% all_reportee = Report.user_reported_comments(reported_comment.reportable_id)%>
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Reported By</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%all_reportee.each do |user|%>

                    <div class="reported-card">
                        <img class="rounded-circle shadow-1-strong me-3 mr-2"
                            src="https://thumbs.dreamstime.com/b/person-gray-photo-placeholder-man-costume-background-146157490.jpg" alt="avatar" width="60" height="60" />
                        
                        <p>
                            <%= user.user.email%>
                        <p> 
                        <p>
                            <%=time_ago_in_words(user.created_at) %>
                        <p> 
                    </div>
                 
                <%end%>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary w-100" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
    </div>

    <div class="mb-2 d-flex justify-content-between align-items-center">
        <div class="">
                <img src="https://thumbs.dreamstime.com/b/person-gray-photo-placeholder-man-costume-background-146157490.jpg" class="rounded-circle" style="width: 50px;"
                alt="Avatar" /> | 
                Comment Of :: <%=reported_comment.user.email%>
        </div>
        <button  type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal<%=reported_comment.reportable.id%>">
            Reported By
        </button>
        
    </div>
    <div class="reported-message-content mb-2">
        <%=reported_comment.reportable.content%>
    </div>
    <div class="reported-comment-statuses">
        <%statuses = reported_comment.reportable.reports.group(:report_status).size%>
        

        <%statuses.each do | item, price |%>
            <button type="button" disabled class="btn btn-danger">
                <%=item%> <span class="badge badge-light"><%= price%></span>
                <span class="sr-only">unread messages</span>
            </button>
        <%end%>
    </div>

    <div class="mt-3">
        <%= form_tag(comment_path(reported_comment.reportable) , remote: true) do |f| %>
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Delete" class="btn btn-danger w-100">
        <% end %>
    </div>
</div>

app/views/reports/_reported_post.html.erb
<%if reported_post.reportable.status==="published"%>
    <div id="reported_post_<%= reported_post.reportable.id%>" class="comment-card">
    <%= render partial:"report_modal", locals:{report:reported_post} %>
    <div class="mb-2 d-flex justify-content-between align-items-center">
        <div class="mb-2">
            <img src="https://thumbs.dreamstime.com/b/person-gray-photo-placeholder-man-costume-background-146157490.jpg" class="rounded-circle" style="width: 50px;"
            alt="Avatar" />  
            Post Of

            : <%=reported_post.reportable.user.email%> |

            <div class="d-inline" id="status-post-chage">
                <%=reported_post.reportable.status%>
            </div>
        </div>
        <button  type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal<%=reported_post.reportable.id%>">
            Reported By
        </button>
    </div>
    
    <div class="reported-message-content mb-2">
        <%=reported_post.reportable.content%>
    </div>
    <div class="reported-comment-statuses">
        <%statuses = reported_post.reportable.reports.group(:report_status).size%>
        

        <%statuses.each do | item, price |%>
            <button type="button" disabled class="btn btn-danger">
                <%=item%> <span class="badge badge-light"><%= price%></span>
                <span class="sr-only">unread messages</span>
            </button>
        <%end%>
    </div>

    <div class="mt-3">
        <%= form_tag(post_path(reported_post.reportable) , remote: true) do |f| %>
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Delete" class="btn btn-danger w-100">
        <% end %>
    </div>

     <div class="mt-3">
        <%= form_tag(post_path(reported_post.reportable) , remote: true) do |f| %>
            <input type="hidden"  name="post[status]" value="unpublished">
            <input type="hidden" name="_method" value="PATCH">
            <input type="hidden" name="post[reportable_id]" value="<%=reported_post.id%>">
            <input type="submit" value="Unpublished Post" class="btn btn-primary w-100">
        <% end %>
    </div>

    </div>
    <%else%>
<%end%>

app/views/reports/all_reported_comment.html.erb
<div class="reported-comment-containor">
   <%if @reported_comments.length===0%>
       <div class="page-wrap d-flex flex-row align-items-center">
         <div class="container">
            <div class="row justify-content-center">
                  <div class="col-md-12 text-center">
                     <span class="display-1 d-block">Opps</span>
                     <div class="mb-4 lead">No Record Found</div>
                     <a href="/" class="btn btn-link">Back to Home</a>
                  </div>
            </div>
         </div>
      </div>
   <%else%>
   <%= render partial: "reports/reported_comment", collection: @reported_comments %>
   <%end%>
</div>

app/views/reports/all_reported_post.html.erb
<div class="reported-comment-containor">
   <%if @reported_posts.length === 0%>
     <div class="page-wrap d-flex flex-row align-items-center">
         <div class="container">
            <div class="row justify-content-center">
                  <div class="col-md-12 text-center">
                        <span class="display-1 d-block">Opps</span>
                     <div class="mb-4 lead">No Record Found</div>
                     <a href="/" class="btn btn-link">Back to Home</a>
                  </div>
            </div>
         </div>
      </div>
   <%else%>
      <%= render partial: "reports/reported_post", collection: @reported_posts %>
   <%end%>
</div>

app/views/reports/create.js.erb
$("#report_<%=@post.id%>").empty().append(`<%= j render partial:"reports/form", locals:{ reportable:@post }%>`);